### ISSUE TITLE
Plan to merge three similar packages

### ISSUE THREAD

**Issue by yuehhua** [SciML/FluxNeuralOperators.jl#36]
Since this project is mature, is there any plan to move to FluxML?

**Comment by foldfelis** [comment]
Yes, sure, is there anything I need to do before I transfer the project？

**Comment by yuehhua** [comment]
@DhairyaLGandhi Could you help this?

**Comment by foldfelis** [comment]
Hi @DhairyaLGandhi, sorry for the late reply. I don't know why I didn't recive the notifecation of the FluxML invitation.
I am currently discuss with @ChrisRackauckas about the future plan. Since both [NeuralOperators.jl](https://github.com/foldfelis/NeuralOperators.jl) and [OperatorLearning.jl](https://github.com/SciML/OperatorLearning.jl) provides solutions to the same problem, it might be a good idea to combine the efforts.

**Comment by ChrisRackauckas** [comment]
There's a third one too: https://github.com/CliMA/OperatorFlux.jl @bischtob @charleskawczynski  and pulling in @pzimbrod . There's nothing wrong with having multiple repos of course, but I think finding the most useful ideas of each repo and folding them together to get top notch performance would be more useful in the end. 

Note that one of the plans I have for where OperatorLearning can go is, given its small neural networks in many cases, we have a fully pre-cached ML library (right now called SimpleChains, being set public fairly soon) that is extremely fast for this small NN case by being fully non-allocating and direct usage of LoopVectorization. At least for the DeepONet parts that can be very useful.

I hope to get a GSoC going and some Julia Lab students going on this as well.

**Comment by bischtob** [comment]
I am down to work together on one repo @ChrisRackauckas ! Would be fantastic to collaborate.

**Comment by pzimbrod** [comment]
I would definitely chime in on the idea of combining our efforts. I think there still is enough functionality and optimizations yet to be implemented and I'd love to see that field grow further in Julia, so why not work on it together 🙂

**Comment by yuehhua** [comment]
@ChrisRackauckas I am also interesting in contributing this work. There is another work for multi-wavelet operator ongoing. My direction is bringing neural operator, GNN and geometric deep learning together. If there is anything I can help, just let me know.

**Comment by ChrisRackauckas** [comment]
Should we have an "internal conference" demoing the 3 packages to try and figure out the difference? The best time I can think of would be 6pm EST (midnight Germany, 7am Taiwan, 3pm west coast. I think that might be the only time where someone isn't in the dreaded 1am-5am range?) 15 minutes each, no slides or anything, just demo the package and figure out what to do? Monday the 21st would work for me. Otherwise I think we'll end up in a bit of deadlock.

**Comment by yuehhua** [comment]
The 21st, 6pm EST? It would be 22nd, 7am Taiwan. It works for me.

**Comment by foldfelis** [comment]
Works for me as well.

**Comment by pzimbrod** [comment]
That would be okay for me as well

**Comment by DhairyaLGandhi** [comment]
Sounds good

**Comment by bischtob** [comment]
Monday 21st works for me.

**Comment by bischtob** [comment]
Where should we meet? Zoom?

**Comment by ChrisRackauckas** [comment]
Invites went out if I have your email. Otherwise just message me your email to get you on there.
